import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { handleHttpRequest } from '../src/http-transport.mjs';

const context = { tenantId: 'TENANT-001', actorId: 'JANITORIAL', role: 'CEO', divisionId: 'JANITORIAL', siteIds: ['C-001'], requestId: 'REQ-1', traceId: 'TRACE-1' };
const request = new EventEmitter(); request.method = 'GET'; request.url = '/v1/me';
const response = { headers: {}, setHeader(key, value) { this.headers[key] = value; }, end(value) { this.body = value; } };
const result = await handleHttpRequest({ request, response, contextResolver: async () => context, apiHandler: input => ({ status: 200, body: { path: input.path, actor: input.context.actorId } }) });
assert.equal(result.status, 200); assert.equal(JSON.parse(response.body).actor, 'JANITORIAL'); assert.equal(response.headers['content-type'], 'application/json; charset=utf-8');
const asyncResponse = { headers: {}, setHeader(key, value) { this.headers[key] = value; }, end(value) { this.body = value; } };
const asyncResult = await handleHttpRequest({ request, response: asyncResponse, contextResolver: async () => context, apiHandler: async input => { await Promise.resolve(); return { status: 200, body: { actor: input.context.actorId } }; } });
assert.equal(asyncResult.status, 200); assert.equal(JSON.parse(asyncResponse.body).actor, 'JANITORIAL');
const asyncErrorResponse = { headers: {}, setHeader(key, value) { this.headers[key] = value; }, end(value) { this.body = value; } };
const asyncError = await handleHttpRequest({ request, response: asyncErrorResponse, contextResolver: async () => context, apiHandler: async () => { throw new Error('internal async detail'); } });
assert.equal(asyncError.status, 400); assert.equal(JSON.parse(asyncErrorResponse.body).error, 'BAD_REQUEST');
assert.equal(asyncErrorResponse.body.includes('internal async detail'), false);
const codedErrorResponse = { headers: {}, setHeader(key, value) { this.headers[key] = value; }, end(value) { this.body = value; } };
const codedError = await handleHttpRequest({ request, response: codedErrorResponse, contextResolver: async () => { const error = new Error('hidden'); error.code = 'DATABASE_CONNECTION_SECRET'; throw error; }, apiHandler: () => ({ status: 200, body: {} }) });
assert.equal(JSON.parse(codedErrorResponse.body).error, 'BAD_REQUEST');
await assert.rejects(() => handleHttpRequest({ request, response, apiHandler: () => ({ status: 200, body: {} }) }), /DEPENDENCIES_REQUIRED/);
const badResponse = { headers: {}, setHeader(key, value) { this.headers[key] = value; }, end(value) { this.body = value; } };
const bad = await handleHttpRequest({ request, badResponse, response: badResponse, contextResolver: async () => { throw new Error('internal context detail'); }, apiHandler: () => ({ status: 200, body: {} }) });
assert.equal(bad.status, 400); assert.equal(JSON.parse(badResponse.body).error, 'BAD_REQUEST');
const notFoundResponse = { headers: {}, setHeader(key, value) { this.headers[key] = value; }, end(value) { this.body = value; } };
const notFound = await handleHttpRequest({ request: Object.assign(new EventEmitter(), { method: 'GET', url: '/v1/unknown' }), response: notFoundResponse, contextResolver: async () => context, apiHandler: () => ({ status: 404, body: { error: 'NOT_FOUND' } }) });
assert.equal(notFound.status, 404);
console.log('HTTP TRANSPORT TEST OK · resolver explícito · JSON · delegación segura');
